branch-defaults:
  master:
    environment: production
environment-defaults:
  production:
    branch: null
    repository: null
global:
  application_name: music-suggestion-tool
  default_ec2_keyname: null
  default_platform: arn:aws:elasticbeanstalk:us-west-1::platform/Node.js running on
    64bit Amazon Linux/4.5.4
  default_region: us-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
